In [3]:
import numpy as np
myarray2=np.array([[1,2,3],[4,5,6],[1,1,1]])
print("shape:",myarray2.shape)
print("size:",myarray2.size)
print("Dimension",myarray2.ndim)
print("Elementype",myarray2.dtype)

shape: (3, 3)
size: 9
Dimension 2
Elementype int32


In [9]:
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

a3 = np.add(a1,a2)
print(a3)

[5 7 9]


In [10]:
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

a3 = np.subtract(a1,a2)
print(a3)

[-3 -3 -3]


In [11]:
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

a3 = np.multiply(a1,a2)
print(a3)

[ 4 10 18]


In [12]:
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

a3 = np.divide(a1,a2)
print(a3)

[0.25 0.4  0.5 ]


In [13]:
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

a3 = np.add(a1,a2)
a3 = np.subtract(a1,a2)
a3 = np.multiply(a1,a2)
a3 = np.divide(a1,a2)
print(a3)

[0.25 0.4  0.5 ]


In [3]:
import numpy as np
myarray = np.array([1,2,3,4,5,6])
print(myarray)
print(type(myarray))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print("Array is of type:",type(arr))
print("No. of dimensions:",arr.ndim)
print("Shape of array:", arr.shape)
print("Size of the array:", arr.size)
print("Array stores elemnt of type:", arr.dtype)

Array is of type: <class 'numpy.ndarray'>
No. of dimensions: 1
Shape of array: (5,)
Size of the array: 5
Array stores elemnt of type: int32


In [5]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("Array is of type:",type(arr))
print("No. of dimensions:",arr.ndim)
print("Shape of array:", arr.shape)
print("Size of the array:", arr.size)
print("Array stores elemnt of type:", arr.dtype)

Array is of type: <class 'numpy.ndarray'>
No. of dimensions: 2
Shape of array: (2, 3)
Size of the array: 6
Array stores elemnt of type: int32


In [6]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array is of type:",type(arr))
print("No. of dimensions:",arr.ndim)
print("Shape of array:", arr.shape)
print("Size of the array:", arr.size)
print("Array stores elemnt of type:", arr.dtype)

Array is of type: <class 'numpy.ndarray'>
No. of dimensions: 2
Shape of array: (3, 3)
Size of the array: 9
Array stores elemnt of type: int32


In [8]:
import numpy as np
arr = np.array([1,2,3,4,5], ndmin=10)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
number of dimensions : 10


In [9]:
arange_array = np.arange(0,11,2)   
print(arange_array)


[ 0  2  4  6  8 10]


In [12]:
arr2 = np.arange(20,0,-1)
print("Reverse Array", arr2)


Reverse Array [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [16]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
import numpy as np
arr = np.empty([3,2], dtype = int)
print(arr)

[[0 0]
 [0 0]
 [0 0]]


In [5]:
import numpy as np
arr1 = np.ones([3,2], dtype = int)
print(arr1)
print("shape:", arr1.shape)
print("size:", arr1.size)
print("Dimensions:", arr1.ndim)
print("Elements type:", arr1.dtype)

[[1 1]
 [1 1]
 [1 1]]
shape: (3, 2)
size: 6
Dimensions: 2
Elements type: int32


In [6]:
import numpy as np
arr = np.array([5,6,7])
x = np.array(arr)
y = np.asarray(arr)
arr[1] = 10
print("array:", x)
print("asarray", y)

array: [5 6 7]
asarray [ 5 10  7]


In [8]:
import numpy as np
arr = np.array([5,6,7])
x = np.array(arr)
y = np.asarray(arr)
arr[2] = 10
print("array:", x)
print("asarray", y)

array: [5 6 7]
asarray [ 5  6 10]


In [9]:
import numpy as np
arr = np.array([5,6,7])
x = np.array(arr)
y = np.asarray(arr)
arr[0] = 10
print("array:", x)
print("asarray", y)

array: [5 6 7]
asarray [10  6  7]


In [11]:
import numpy as np
arr = np.array([5,6,7])
x = np.array(arr)
y = np.asarray(arr)
arr[0] = 10
arr[1] = 9
arr[2] = 8
print("array:", x)
print("asarray", y)

array: [5 6 7]
asarray [10  9  8]


In [15]:
#bitwise operators
import numpy as np
a = 12
b = 25
print("binary representation of a:", bin(a))
print("binary representation of b:", bin(b))
print("bitwise and of a and b:", np.bitwise_and(a,b))

binary representation of a: 0b1100
binary representation of b: 0b11001
bitwise and of a and b: 8


In [14]:
import numpy as np
a = 12
b = 25
print("binary representation of a:", bin(a))
print("binary representation of b:", bin(b))
print("bitwise or of a and b:", np.bitwise_or(a,b))

binary representation of a: 0b1100
binary representation of b: 0b11001
bitwise or of a and b: 29


In [16]:
import numpy as np
a = 10
print('left shift of 10 by two positions:')
print(np.left_shift(10,2))

left shift of 10 by two positions:
40


In [18]:
import numpy as np
a = 10
print('left shift of 10 by one positions:')
print(np.left_shift(10,1))

left shift of 10 by one positions:
20


In [19]:
import numpy as np
a = 10
print('left shift of 10 by five positions:')
print(np.left_shift(10,5))

left shift of 10 by five positions:
320


In [20]:
import numpy as np
a = 40
print('right shift of 40 by two positions:')
print(np.right_shift(40,2))

right shift of 40 by two positions:
10


In [21]:
import numpy as np
a = 40
print('right shift of 40 by one positions:')
print(np.right_shift(40,1))

right shift of 40 by one positions:
20


In [8]:
# Stringn funtions
import numpy as np
print ('Concate two strings:')
print (np.char.add(['hello'],['xyz']))
print ('\n')

Concate two strings:
['helloxyz']




In [6]:
import numpy as np 
print (np.char.multiply('Hello',3))



HelloHelloHello


In [11]:
import numpy as np 
# np.char.center(arr, width,fillchar) 
print (np.char.center('hello', 20,fillchar = '*'))


*******hello********


In [12]:
import numpy as np 
print( np.char.capitalize('hello world'))


Hello world


In [13]:
#Operations on Numpy
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b 
print(c)

[5 7 9]


In [14]:
import numpy as np
a = np.array([10,20,30])
b = np.array([1,2,3])
print(a.shape)
print(b.shape)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

(3,)
(3,)
[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
